name: devroom-frontend-cicd
on:
  push:
    branches: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Dependencies
        run: |
          npm install

      - name: Copy NEXT_ENV
        run: echo "${{ secrets.NEXT_ENV }}" > ./.env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: devroom-frontend-cicd
        run: |
          npm run deploy

      - name: Upload S3 code
        run: aws s3 sync ./out s3://devroombucket/frontend --acl public-read --delete